services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: hands-up-zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    platform: linux/amd64

  kafka:
    image: wurstmeister/kafka
    container_name: hands-up-kafka
    ports:
      - "${KAFKA_PORT}:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: hands-up-zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://hands-up-kafka:9092,OUTSIDE://${KAFKA_ADVERTISED_HOST_NAME}:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_RETENTION_HOURS: 72       # 필요시: 로그 보관 기간
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms128M"
    depends_on:
      - zookeeper
    platform: linux/amd64